# Generated by Django 5.2.6 on 2025-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
